modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "chineselanterns"
version = "${version}"
displayName = "ChineseLanterns"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.chineselanterns]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chineselanterns]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chineselanterns]]
modId = "architectury"
type = "required"
versionRange = "[12.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "chineselanterns.mixins.json"
